---
title: "Disseminating Collaborative and Reproducible Research"
subtitle: "Workshop Schedule"
author: "Dr Mine Dogucu and Dr Sinem Demirci"
format: html
editor: visual
---

```{r}
#| echo: false
library(fontawesome)
```

# Before the Workshop

-   Make sure to have created a **GitHub account** <a href = "https://github.com/" target="_blank"> `r fontawesome::fa(name = "link")`</a> and report your username in this **short survey** <a href = "https://forms.office.com/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwh_yQS1QwCtAhUd1IALGUPFUOUxQOTZNTzZaUUpQTDJOVExPS00xR1VCQi4u" target="_blank"> `r fontawesome::fa(name = "link")`</a>. GitHub usernames are used in professional settings (e.g. on CVs), thus you may want to pick a username that you do not mind sharing publicly.

-   A few days after filling out the survey, you will receive an invitation to join our **GitHub organization**, please accept this invitation.

-   **Install R** <a href = "https://mirror.las.iastate.edu/CRAN/" target="_blank"> `r fontawesome::fa(name = "link")`</a> Yes, you do need to download and install R even if you have downloaded before. There is a newer version.

-   **Install RStudio** <a href = "https://www.rstudio.com/products/rstudio/download/" target="_blank"> `r fontawesome::fa(name = "link")`</a> Yes, you do need to download and install RStudio even if you have downloaded before. There is a newer version. Download the free Desktop version.

-   **Install and setup git** <a href = "https://drive.google.com/file/d/1_I9fOIpBs1Oc1EkFKd-BMe_X2_NpP3um/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "video")` </a> <a href = "https://disseminate-collaborate-reproduce.github.io/slides/00-install-git.html" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>

-   **Test your installations** <a href = "https://drive.google.com/file/d/1rTOWcau0oTPvxb-pCRHAXIRXikjs3Lyf/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "video")`</a>. If you have filled out the survey later than usual, your test repo may not be available. Please contact us in that case.

# During the Workshop

The workshop will be divided into six parts. For each part you will be provided a repo which you will get to work with hands-on. Note that the `username` in repo names refer to your own GitHub username.

| Content                        | Slide   | Repo Name |
|--------------------------------|---------|-----------|
| Introduction to Git and GitHub | <a href = "https://disseminate-collaborate-reproduce.github.io/slides/01-intro-git.html" target="_blank"> `r fontawesome::fa(name = "laptop")`</a> | `01-intro-github-username`    |
| Introduction to Quarto         | no slides         | `02-intro-quarto-username`          |
| Writing a Manuscript           | <a href = "https://disseminate-collaborate-reproduce.github.io/slides/03-writing-a-manuscript.html" target="_blank"> `r fontawesome::fa(name = "laptop")`</a>        |`03-manuscript`           |
| Collaboration on GitHub        | <a href = "https://disseminate-collaborate-reproduce.github.io/slides/04-collaboration.html" target="_blank"> `r fontawesome::fa(name = "laptop")`</a>        |`04-collaborative-manuscript`           |
| Making a Website               | <a href = "https://disseminate-collaborate-reproduce.github.io/slides/05-making-a-website.html" target="_blank"> `r fontawesome::fa(name = "laptop")`</a>         | you will create this repo          |
| Reproducible Workflows         |<a href = "https://disseminate-collaborate-reproduce.github.io/slides/06-reproducible-workflows.html" target="_blank"> `r fontawesome::fa(name = "laptop")`</a>         | `06-reproduce`          |
